name: pharmdel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#  #Firebase
  firebase_dynamic_links: ^5.0.17
  cloud_firestore: ^4.4.5
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17

  #Database
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.13
  path: ^1.8.2
  path_provider: ^2.0.13

  flutter_ringtone_player: ^3.2.0
  overlay_support: ^2.1.0

#  # Google Map
#  geocoding: ^2.0.5
#  geolocator: ^9.0.2
#  maps_launcher: ^2.0.1


  dio: ^5.0.3
  get: ^4.6.5
  camera: ^0.10.3+2
  page_transition: ^2.0.9
  pull_to_refresh: ^2.0.0
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_screenutil: ^5.7.0
  loading_overlay: ^0.3.0
  delayed_display: ^2.0.0
  share_plus: ^6.3.1
  photo_view: ^0.14.0
  sizer: ^2.0.15
  preload_page_view: ^0.1.6
  fluttertoast: ^8.2.1
  socket_io_client: ^2.0.1

  connectivity_plus: ^3.0.3
  permission_handler: ^10.2.0
  image_picker: ^0.8.7
  shared_preferences: ^2.0.18
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: ^0.12.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  logger: ^1.3.0
  local_auth: ^2.1.6
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^20.4.54
  barcode_scan2: ^4.2.4
  lottie: ^2.3.0
  location_permissions: ^4.0.1
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
#dropdown button
  dropdown_button2: ^2.0.0
  maps_launcher: ^2.2.0
  webview_flutter: ^4.0.7

  #flutter_secure_storage
  flutter_secure_storage: ^8.0.0

  xml2json: ^5.3.6
  flutter_barcode_scanner: ^2.0.0
  flutter_beep: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  flutter_lints: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/logo/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa_bold.otf
        - asset: assets/fonts/nexa_light.otf
        - asset: assets/fonts/NexaBlack.otf
        - asset: assets/fonts/NexaBlackItalic.otf
        - asset: assets/fonts/NexaBold.otf
        - asset: assets/fonts/NexaBoldItalic.otf
        - asset: assets/fonts/NexaBook.otf
        - asset: assets/fonts/NexaBookItalic.otf
        - asset: assets/fonts/NexaHeavy.otf
        - asset: assets/fonts/NexaHeavyItalic.otf
        - asset: assets/fonts/NexaLight.otf
        - asset: assets/fonts/NexaLightItalic.otf
        - asset: assets/fonts/NexaRegular.otf
        - asset: assets/fonts/NexaRegularItalic.otf
        - asset: assets/fonts/NexaThin.otf
        - asset: assets/fonts/NexaThinItalic.otf
        - asset: assets/fonts/NexaXBold.otf
        - asset: assets/fonts/NexaXBoldItalic.otf


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo_white.jpg"
